class StorageKey {
  static USER_TOKEN = "SECURE_STORAGE_USER_PUBKEY";
  static USER_PRIVKEY = "SECURE_STORAGE_USER_PRIVKEY";
  static USER_PROFILE = "STORAGE_USER_PROFILE";
  static USER_CATEGORY_MAJOR = "STORAGE_USER_CATEGORY_MAJOR";
}

export default StorageKey;
